---
title: "512 Final Project - Random Forest"
author: "Mia Mayerhofer"
date: "2023-04-21"
output: html_document
---

```{r}
# Load libraries
library(randomForest)
library(caTools)
library(caret)
library(reprtree)
```

```{r}
# Read in the data
setwd("/Users/miamayerhofer/ANLY_512_Final_Project")
data <- read.csv("data/modified/films_gendered.csv")
```

```{r}
# View the data
head(data)
```

```{r}
# Make bechdel_pass col into factor
data <- transform(data, bechdel_pass = as.factor(bechdel_pass))
```

```{r}
# Get the number of NAs per column to decide whether or not to drop them
colSums(is.na(data))
```

```{r}
# Make a data frame without NAs
data_no_nas <- data[complete.cases(data), ]
dim(data_no_nas)
```

```{r}
# Are all the titles unique?
length(unique(data_no_nas$title_id)) # should be 858
# Only select certain columns - remove title id, title name, and test
subset_df <- data_no_nas[, c(-1, -2, -48)]
```

```{r}
# Split into train and test
set.seed(42)
indices <- sample(nrow(subset_df), floor(nrow(subset_df) * 0.7))
train <- subset_df[indices,]
test <- subset_df[-indices,]
dim(train)
dim(test)
```

### Random Forest Classification

```{r}
# Initialize a baseline random forest model and train
set.seed(42)
rf_model <- randomForest(
  bechdel_pass ~ .,
  data = train,
  ntree = 1000
)
```

```{r}
# Predict the test set Bechdel scores
preds <- predict(rf_model, newdata = test[-46])
```

```{r}
# Confusion matrix
confusionMatrix(preds, test$bechdel_pass)
```
```{r}
# Plot confusion matrix
cm <- confusionMatrix(factor(preds), factor(test$bechdel_pass), dnn = c("Prediction", "Reference"))

plt <- as.data.frame(cm$table)
plt$Prediction <- factor(plt$Prediction, levels=rev(levels(plt$Prediction)))

ggplot(plt, aes(Prediction,Reference, fill= Freq)) +
        geom_tile() + geom_text(aes(label=Freq)) +
        scale_fill_gradient(low="white", high="navy") +
        labs(x = "Actual Bechdel Result", y = "Predicted Bechdel Result") +
        scale_x_discrete(labels=c("True","False","True","False")) +
        scale_y_discrete(labels=c("False","True","False","True"))
```

```{r}
# Plot a tree from the forest
reprtree:::plot.getTree(rf_model)
```

```{r}
# Get predictor importance
pred_importance <- importance(rf_model)
indices <- order(pred_importance[, "MeanDecreaseGini"], decreasing = TRUE)
sorted_importance <- pred_importance[indices, ]
sorted_importance
```

```{r}
# Make a plot showing this importance
plot_data <- as.data.frame(sorted_importance)
plot_data$predictor <- row.names(plot_data)

ggplot(plot_data, aes(x = reorder(predictor, sorted_importance), y = sorted_importance)) +
  geom_bar(stat = "identity") + coord_flip() +   
  labs(title = "Importance of Predictors of Bechdel Test Result",
       x = "Predictor",
       y = "Importance")
```


### Random Forest Classification Subset

```{r}
# Subset the data
names <- c("pct_female_producers", "pct_female_castmembers", "pct_female_directors", "pct_female_writers", "bechdel_pass")
train_subset <- train[, names]
test_subset <- test[, names]
```

```{r}
# Define the model
rf_model2 <- randomForest(bechdel_pass ~ ., data = train_subset, ntree = 1000)
# Predict the budget on the test set
preds2 <- predict(rf_model2, newdata = test_subset[-5])
# Plot a tree
reprtree:::plot.getTree(rf_model2)
# Confusion matrix
confusionMatrix(preds2, test_subset$bechdel_pass)
```

```{r}
# Plot confusion matrix
cm <- confusionMatrix(factor(preds2), factor(test_subset$bechdel_pass), dnn = c("Prediction", "Reference"))

plt <- as.data.frame(cm$table)
plt$Prediction <- factor(plt$Prediction, levels=rev(levels(plt$Prediction)))

ggplot(plt, aes(Prediction,Reference, fill= Freq)) +
        geom_tile() + geom_text(aes(label=Freq)) +
        scale_fill_gradient(low="white", high="navy") +
        labs(x = "Actual Bechdel Result", y = "Predicted Bechdel Result") +
        scale_x_discrete(labels=c("True","False","True","False")) +
        scale_y_discrete(labels=c("False","True","False","True"))
```

### References
https://towardsdatascience.com/random-forest-in-r-f66adf80ec9

https://github.com/araastat/reprtree/issues/12
